on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             run: actions/checkout@v4
           - name: say hello  
             run: echo "Hi from github actions!"
           - name: show current directory
             run: pwd
           - name: List files
             run: ls -la
